// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: league.sql

package sqlc

import (
	"context"
)

const createMatch = `-- name: CreateMatch :one

INSERT INTO matches (season_id, week, home_team_id, away_team_id)
VALUES ($1, $2, $3, $4)
RETURNING id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at
`

type CreateMatchParams struct {
	SeasonID   int64
	Week       int32
	HomeTeamID int64
	AwayTeamID int64
}

// Matches --------------------------------------------------------------------
func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.SeasonID,
		arg.Week,
		arg.HomeTeamID,
		arg.AwayTeamID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Week,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.PlayedAt,
	)
	return i, err
}

const createSeason = `-- name: CreateSeason :one

INSERT INTO seasons (name, total_weeks) VALUES ($1, $2) RETURNING id, name, current_week, total_weeks, created_at
`

type CreateSeasonParams struct {
	Name       string
	TotalWeeks int32
}

// Seasons --------------------------------------------------------------------
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason, arg.Name, arg.TotalWeeks)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentWeek,
		&i.TotalWeeks,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMatchesBySeason = `-- name: DeleteMatchesBySeason :exec
DELETE FROM matches WHERE season_id = $1
`

func (q *Queries) DeleteMatchesBySeason(ctx context.Context, seasonID int64) error {
	_, err := q.db.Exec(ctx, deleteMatchesBySeason, seasonID)
	return err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM seasons WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSeason, id)
	return err
}

const getCurrentSeason = `-- name: GetCurrentSeason :one
SELECT id, name, current_week, total_weeks, created_at FROM seasons ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCurrentSeason(ctx context.Context) (Season, error) {
	row := q.db.QueryRow(ctx, getCurrentSeason)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentWeek,
		&i.TotalWeeks,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id int64) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Week,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.PlayedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, short_name, attack_strength, defense_strength, home_advantage FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.AttackStrength,
		&i.DefenseStrength,
		&i.HomeAdvantage,
	)
	return i, err
}

const listMatchesBySeason = `-- name: ListMatchesBySeason :many
SELECT id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at FROM matches WHERE season_id = $1 ORDER BY week, id
`

func (q *Queries) ListMatchesBySeason(ctx context.Context, seasonID int64) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Week,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByWeek = `-- name: ListMatchesByWeek :many
SELECT id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at FROM matches WHERE season_id = $1 AND week = $2 ORDER BY id
`

type ListMatchesByWeekParams struct {
	SeasonID int64
	Week     int32
}

func (q *Queries) ListMatchesByWeek(ctx context.Context, arg ListMatchesByWeekParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByWeek, arg.SeasonID, arg.Week)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Week,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many

SELECT id, name, short_name, attack_strength, defense_strength, home_advantage FROM teams ORDER BY id
`

// Teams ----------------------------------------------------------------------
func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.AttackStrength,
			&i.DefenseStrength,
			&i.HomeAdvantage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnplayedMatchesByWeek = `-- name: ListUnplayedMatchesByWeek :many
SELECT id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at FROM matches
WHERE season_id = $1 AND week = $2 AND played_at IS NULL
ORDER BY id
`

type ListUnplayedMatchesByWeekParams struct {
	SeasonID int64
	Week     int32
}

func (q *Queries) ListUnplayedMatchesByWeek(ctx context.Context, arg ListUnplayedMatchesByWeekParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listUnplayedMatchesByWeek, arg.SeasonID, arg.Week)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Week,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMatchResult = `-- name: RecordMatchResult :one
UPDATE matches
SET home_goals = $2, away_goals = $3, played_at = NOW()
WHERE id = $1 AND played_at IS NULL
RETURNING id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at
`

type RecordMatchResultParams struct {
	ID        int64
	HomeGoals *int32
	AwayGoals *int32
}

func (q *Queries) RecordMatchResult(ctx context.Context, arg RecordMatchResultParams) (Match, error) {
	row := q.db.QueryRow(ctx, recordMatchResult, arg.ID, arg.HomeGoals, arg.AwayGoals)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Week,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.PlayedAt,
	)
	return i, err
}

const setSeasonWeek = `-- name: SetSeasonWeek :one
UPDATE seasons SET current_week = $2 WHERE id = $1 RETURNING id, name, current_week, total_weeks, created_at
`

type SetSeasonWeekParams struct {
	ID          int64
	CurrentWeek int32
}

func (q *Queries) SetSeasonWeek(ctx context.Context, arg SetSeasonWeekParams) (Season, error) {
	row := q.db.QueryRow(ctx, setSeasonWeek, arg.ID, arg.CurrentWeek)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentWeek,
		&i.TotalWeeks,
		&i.CreatedAt,
	)
	return i, err
}

const updateMatchScore = `-- name: UpdateMatchScore :one
UPDATE matches
SET home_goals = $2, away_goals = $3
WHERE id = $1 AND played_at IS NOT NULL
RETURNING id, season_id, week, home_team_id, away_team_id, home_goals, away_goals, played_at
`

type UpdateMatchScoreParams struct {
	ID        int64
	HomeGoals *int32
	AwayGoals *int32
}

func (q *Queries) UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchScore, arg.ID, arg.HomeGoals, arg.AwayGoals)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Week,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.PlayedAt,
	)
	return i, err
}
