// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	ID         int64
	SeasonID   int64
	Week       int32
	HomeTeamID int64
	AwayTeamID int64
	HomeGoals  *int32
	AwayGoals  *int32
	PlayedAt   pgtype.Timestamptz
}

type Season struct {
	ID          int64
	Name        string
	CurrentWeek int32
	TotalWeeks  int32
	CreatedAt   pgtype.Timestamptz
}

type Team struct {
	ID              int64
	Name            string
	ShortName       string
	AttackStrength  float64
	DefenseStrength float64
	HomeAdvantage   float64
}
